# Generated by Django 2.2.2 on 2019-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0004_auto_20190627_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
