# Generated by Django 2.2.2 on 2019-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0005_auto_20190628_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
