# Generated by Django 2.2.2 on 2019-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0007_scrappeddata_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappeddata',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
