# Generated by Django 2.2.2 on 2019-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0008_scrappeddata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='link',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
